In [1]:
import pandas as pd
import numpy as np
from sklearn.cross_validation import train_test_split
import math
import matplotlib as plt

//anaconda/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
train = pd.read_csv('/Users/sanchitsharma/Downloads/titanic_train_data.csv')

In [3]:
train.info


<bound method DataFrame.info of      Unnamed: 0  Survived  Pclass   Age  SibSp  Parch      Fare  male  Q  S
0             0         0       3  22.0      1      0    7.2500     1  0  1
1             1         1       1  38.0      1      0   71.2833     0  0  0
2             2         1       3  26.0      0      0    7.9250     0  0  1
3             3         1       1  35.0      1      0   53.1000     0  0  1
4             4         0       3  35.0      0      0    8.0500     1  0  1
5             5         0       3  25.0      0      0    8.4583     1  1  0
6             6         0       1  54.0      0      0   51.8625     1  0  1
7             7         0       3   2.0      3      1   21.0750     1  0  1
8             8         1       3  27.0      0      2   11.1333     0  0  1
9             9         1       2  14.0      1      0   30.0708     0  0  0
10           10         1       3   4.0      1      1   16.7000     0  0  1
11           11         1       1  58.0      0      0   

In [4]:
y = train['Survived']

In [5]:
train.drop('Survived', inplace = True, axis =1)

In [6]:
train.drop('Unnamed: 0', inplace = True, axis=1)


In [7]:
train.drop(['Fare', 'Q', 'S'], inplace = True, axis=1)

In [8]:
x_train, x_cv, y_train, y_cv = train_test_split(train, y, test_size =0.25)

In [9]:
x_train

Pclass   Age  SibSp  Parch  male
553       3  22.0      0      0     0
825       3  25.0      0      0     1
109       1  47.0      0      0     1
118       3   2.0      4      2     0
879       3  33.0      0      0     1
693       1  60.0      0      0     1
408       3  25.0      3      1     0
568       3  32.0      0      0     1
353       3  25.0      0      0     1
728       3  25.0      1      0     0
129       3  33.0      0      0     1
745       3  16.0      1      1     1
730       3  11.0      0      0     1
490       3  21.0      0      0     1
764       1  51.0      1      0     0
713       2  52.0      0      0     1
14        3  14.0      0      0     0
542       2  32.0      1      0     1
137       3  16.0      0      0     1
97        2  34.0      0      1     0
351       3  15.0      1      1     1
390       3  21.0      0      0     1
68        3  26.0      2      0     1
813       3  30.5      0      0     1
138       1  24.0      0      0     1
876       3  25.0      0      0     1
104       3  28.0      0      0     1
278       3  35.0      1      1     0
787       3   1.0      1      2     1
401       3  21.0      1      0     0
..      ...   ...    ...    ...   ...
773       2  54.0      1      3     0
404       2  34.0      1      0     1
886       3  25.0      1      2     0
348       3  42.0      0      0     1
607       2  22.0      1      2     0
648       3  23.0      0      0     0
264       2  36.0      0      0     1
685       3  14.0      4      1     1
285       3  30.0      0      0     1
742       3  24.0      1      0     1
164       3   9.0      0      2     1
276       2  30.0      0      0     1
9         2  14.0      1      0     0
601       1  38.0      0      0     1
651       3  21.0      0      0     1
657       2  23.0      0      0     1
209       3  24.0      0      0     1
860       1  48.0      0      0     0
135       1  19.0      0      2     0
644       1  48.0      1      0     1
709       1  24.0      0      0     0
94        3  25.0      0      0     1
98        2  34.0      1      0     1
268       1  35.0      0      0     0
571       1  36.0      0      0     1
10        3   4.0      1      1     0
257       1  35.0      0      0     0
705       2  45.0      0      0     0
171       3   1.0      1      1     0
636       2  31.0      1      1     1

[666 rows x 5 columns]

In [10]:
x_train = np.asmatrix(x_train)
x_cv = np.asmatrix(x_cv)

In [11]:
y_train = np.reshape(y_train, (666,1))
y_cv = np.reshape(y_cv,(223,1))

//anaconda/lib/python3.5/site-packages/numpy/core/fromnumeric.py:57: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  return getattr(obj, method)(*args, **kwds)


In [12]:
x_train.std(axis=0)

matrix([[  0.83818892,  13.28123035,   1.1533721 ,   0.80232041,
           0.47297297]])

In [13]:
x_train = (x_train - x_train.mean(axis=0)) / x_train.std(axis=0)

In [14]:
def sigmoid(z):
    return 1.0/(1+ np.exp(-z))

In [15]:
x_train= np.insert(x_train,0,values= 1, axis=1)

m = y_train.shape[0]


In [71]:
def cost_function(theta, x, y, alpha =0.003):
    J=0
    grad = np.zeros(theta.shape)
    J = (1/m) * np.sum(np.dot(np.transpose(-y),np.log(sigmoid(np.dot(x, theta)))) - np.dot(np.transpose(1-y), np.log(1-sigmoid(np.dot(x,theta)))))
    grad = (alpha/m) * (np.dot(np.transpose(x),sigmoid(np.dot(x,theta)) - y))
    return (J, grad)
    

In [72]:
theta = np.zeros((x_train.shape[1],1))

In [18]:
x_train.shape

(666, 6)

In [19]:
cost_cv = np.zeros(())

In [73]:
for i in range(0,500):
    (J, grad)= cost_function(theta, x_train, y_train)
    theta = theta - grad

In [21]:
grad.shape

(6, 1)

In [22]:
(J, grad)= cost_function(theta, x_train, y_train)

In [23]:
np.transpose(x_train).shape

(6, 666)

In [24]:
sigmoid(np.dot(x_train, theta)).shape

(666, 1)

In [25]:
y_train.shape

(666, 1)

In [74]:
theta

matrix([[-0.15818853],
        [-0.20058141],
        [-0.04503824],
        [-0.03389511],
        [ 0.05852843],
        [-0.33365337]])

In [60]:
def predict(z):
    if z>= 0.5:
        return 1
    else:
        return 0
    

In [28]:
x_cv = np.insert(x_cv,0,1,axis=1)

In [29]:
hyp = sigmoid(np.dot(x_cv, theta))

In [30]:
pred = np.apply_along_axis(predict,axis=1,arr= hyp)

In [31]:
pred = pred.reshape((223,1))

In [32]:
from sklearn.metrics import classification_report
print(classification_report(pred, y_cv))

             precision    recall  f1-score   support

          0       1.00      0.59      0.74       223
          1       0.00      0.00      0.00         0

avg / total       1.00      0.59      0.74       223



//anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1115: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [33]:
test = pd.read_csv('/Users/sanchitsharma/Downloads/test.csv')

In [34]:
test

PassengerId  Pclass                                               Name  \
0            892       3                                   Kelly, Mr. James   
1            893       3                   Wilkes, Mrs. James (Ellen Needs)   
2            894       2                          Myles, Mr. Thomas Francis   
3            895       3                                   Wirz, Mr. Albert   
4            896       3       Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
5            897       3                         Svensson, Mr. Johan Cervin   
6            898       3                               Connolly, Miss. Kate   
7            899       2                       Caldwell, Mr. Albert Francis   
8            900       3          Abrahim, Mrs. Joseph (Sophie Halaut Easu)   
9            901       3                            Davies, Mr. John Samuel   
10           902       3                                   Ilieff, Mr. Ylio   
11           903       1                         Jones, Mr. Charles Cresson   
12           904       1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)   
13           905       2                               Howard, Mr. Benjamin   
14           906       1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...   
15           907       2      del Carlo, Mrs. Sebastiano (Argenia Genovesi)   
16           908       2                                  Keane, Mr. Daniel   
17           909       3                                  Assaf, Mr. Gerios   
18           910       3                       Ilmakangas, Miss. Ida Livija   
19           911       3              Assaf Khalil, Mrs. Mariana (Miriam")"   
20           912       1                             Rothschild, Mr. Martin   
21           913       3                          Olsen, Master. Artur Karl   
22           914       1               Flegenheim, Mrs. Alfred (Antoinette)   
23           915       1                    Williams, Mr. Richard Norris II   
24           916       1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
25           917       3                            Robins, Mr. Alexander A   
26           918       1                       Ostby, Miss. Helene Ragnhild   
27           919       3                                  Daher, Mr. Shedid   
28           920       1                            Brady, Mr. John Bertram   
29           921       3                                  Samaan, Mr. Elias   
..           ...     ...                                                ...   
388         1280       3                               Canavan, Mr. Patrick   
389         1281       3                        Palsson, Master. Paul Folke   
390         1282       1                         Payne, Mr. Vivian Ponsonby   
391         1283       1     Lines, Mrs. Ernest H (Elizabeth Lindsey James)   
392         1284       3                      Abbott, Master. Eugene Joseph   
393         1285       2                               Gilbert, Mr. William   
394         1286       3                           Kink-Heilmann, Mr. Anton   
395         1287       1     Smith, Mrs. Lucien Philip (Mary Eloise Hughes)   
396         1288       3                               Colbert, Mr. Patrick   
397         1289       1  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...   
398         1290       3                     Larsson-Rondberg, Mr. Edvard A   
399         1291       3                           Conlon, Mr. Thomas Henry   
400         1292       1                            Bonnell, Miss. Caroline   
401         1293       2                                    Gale, Mr. Harry   
402         1294       1                     Gibson, Miss. Dorothy Winifred   
403         1295       1                             Carrau, Mr. Jose Pedro   
404         1296       1                       Frauenthal, Mr. Isaac Gerald   
405         1297       2       Nourney, Mr. Alfred (Baron von Drachstedt")"   
406         1298       2                          Ware,

In [38]:
y_test = test.drop(['Ticket', 'Name','Cabin','Embarked_Q','Fare','Embarked_S'], axis=1)

ValueError: labels ['Embarked_Q' 'Embarked_S'] not contained in axis

In [36]:
y_test = pd.get_dummies(y_test,columns=['Sex', 'Embarked'],drop_first = True)

In [40]:
y_test = y_test.drop(['Embarked_Q', 'Embarked_S', 'Fare'], axis =1)

In [92]:
x_test = y_test[['Pclass', 'Age','SibSp', 'Parch', 'Sex_male']]

In [95]:
x_test.insert(0,column = 'ones',value =1)

In [96]:
x_test

ones    Pclass           Age     SibSp     Parch  Sex_male
0       1  0.872436  3.345917e-01 -0.498872 -0.399769  0.755024
1       1  0.872436  1.323944e+00  0.616254 -0.399769 -1.321292
2       1 -0.315441  2.511166e+00 -0.498872 -0.399769  0.755024
3       1  0.872436 -2.590195e-01 -0.498872 -0.399769  0.755024
4       1  0.872436 -6.547602e-01  0.616254  0.619154 -1.321292
5       1  0.872436 -1.287945e+00 -0.498872 -0.399769  0.755024
6       1  0.872436 -2.157502e-02 -0.498872 -0.399769 -1.321292
7       1 -0.315441 -3.381676e-01  0.616254  0.619154  0.755024
8       1  0.872436 -9.713528e-01 -0.498872 -0.399769 -1.321292
9       1  0.872436 -7.339084e-01  1.731380 -0.399769  0.755024
10      1  0.872436 -2.530716e-15 -0.498872 -0.399769  0.755024
11      1 -1.503319  1.244795e+00 -0.498872 -0.399769  0.755024
12      1 -1.503319 -5.756121e-01  0.616254 -0.399769 -1.321292
13      1 -0.315441  2.590314e+00  0.616254 -0.399769  0.755024
14      1 -1.503319  1.323944e+00  0.616254 -0.399769 -1.321292
15      1 -0.315441 -4.964639e-01  0.616254 -0.399769 -1.321292
16      1 -0.315441  3.741657e-01 -0.498872 -0.399769  0.755024
17      1  0.872436 -7.339084e-01 -0.498872 -0.399769  0.755024
18      1  0.872436 -2.590195e-01  0.616254 -0.399769 -1.321292
19      1  0.872436  1.165647e+00 -0.498872 -0.399769 -1.321292
20      1 -1.503319  1.957129e+00  0.616254 -0.399769  0.755024
21      1  0.872436 -1.683686e+00 -0.498872  0.619154  0.755024
22      1 -1.503319 -2.530716e-15 -0.498872 -0.399769 -1.321292
23      1 -1.503319 -7.339084e-01 -0.498872  0.619154  0.755024
24      1 -1.503319  1.403092e+00  0.616254  2.656999 -1.321292
25      1  0.872436  1.561388e+00  0.616254 -0.399769  0.755024
26      1 -1.503319 -6.547602e-01 -0.498872  0.619154 -1.321292
27      1  0.872436 -6.151861e-01 -0.498872 -0.399769  0.755024
28      1 -1.503319  8.490546e-01 -0.498872 -0.399769  0.755024
29      1  0.872436 -2.530716e-15  1.731380 -0.399769  0.755024
..    ...       ...           ...       ...       ...       ...
388     1  0.872436 -7.339084e-01 -0.498872 -0.399769  0.755024
389     1  0.872436 -1.921131e+00  2.846506  0.619154  0.755024
390     1 -1.503319 -5.756121e-01 -0.498872 -0.399769  0.755024
391     1 -1.503319  1.640536e+00 -0.498872  0.619154 -1.321292
392     1  0.872436 -1.367094e+00 -0.498872  1.638076  0.755024
393     1 -0.315441  1.323944e+00 -0.498872 -0.399769  0.755024
394     1  0.872436 -1.007232e-01  2.846506  0.619154  0.755024
395     1 -1.503319 -9.713528e-01  0.616254 -0.399769 -1.321292
396     1  0.872436 -4.964639e-01 -0.498872 -0.399769  0.755024
397     1 -1.503319  1.403092e+00  0.616254  0.619154 -1.321292
398     1  0.872436 -6.547602e-01 -0.498872 -0.399769  0.755024
399     1  0.872436  5.757313e-02 -0.498872 -0.399769  0.755024
400     1 -1.503319 -2.157502e-02 -0.498872 -0.399769 -1.321292
401     1 -0.315441  6.116102e-01  0.616254 -0.399769  0.755024
402     1 -1.503319 -6.547602e-01 -0.498872  0.619154 -1.321292
403     1 -1.503319 -1.050501e+00 -0.498872 -0.399769  0.755024
404     1 -1.503319  1.007351e+00  0.616254 -0.399769  0.755024
405     1 -0.315441 -8.130565e-01 -0.498872 -0.399769  0.755024
406     1 -0.315441 -5.756121e-01  0.616254 -0.399769  0.755024
407     1 -1.503319  1.561388e+00  0.616254  0.619154  0.755024
408     1  0.872436 -2.530716e-15 -0.498872 -0.399769 -1.321292
409     1  0.872436 -2.158575e+00  0.616254  0.619154 -1.321292
410     1  0.872436 -2.530716e-15 -0.498872 -0.399769 -1.321292
411     1 -1.503319  5.324620e-01  0.616254 -0.399769 -1.321292
412     1  0.872436 -1.798713e-01 -0.498872 -0.399769 -1.321292
413     1  0.872436 -2.530716e-15 -0.498872 -0.399769  0.755024
414     1 -1.503319  6.907583e-01 -0.498872 -0.399769 -1.321292
415     1  0.872436  6.511842e-01 -0.498872 -0.399769  0.755024
416     1  0.872436 -2.530716e-15 -0.498872 -0.399769  0.755024
417     1  0.872436 -2.530716e-15  0.616254  0.619154  0.755024

[418 rows x 6 columns]

In [93]:
x_test.fillna(x_test['Age'].mean(), axis=1, inplace =True)

//anaconda/lib/python3.5/site-packages/pandas/core/frame.py:2754: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  downcast=downcast, **kwargs)


In [94]:
x_test = (x_test - x_test.mean(axis=0)) / x_test.std(axis=0)

In [97]:
hyp_res = sigmoid(np.dot(x_test, theta))

In [98]:
pred_res = np.apply_along_axis(predict,axis=1,arr= hyp_res)

In [99]:
pred_res

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0,

In [100]:
pred_res = pred_res.reshape((418,1))

In [101]:
pred_res

array([[0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
    

In [102]:
submission = pd.DataFrame(pred_res, columns = ['Survived'], index = y_test['PassengerId'])

In [103]:
submission

Survived
PassengerId          
892                 0
893                 1
894                 0
895                 0
896                 1
897                 0
898                 1
899                 0
900                 1
901                 0
902                 0
903                 0
904                 1
905                 0
906                 1
907                 1
908                 0
909                 0
910                 1
911                 1
912                 0
913                 0
914                 1
915                 0
916                 1
917                 0
918                 1
919                 0
920                 0
921                 0
...               ...
1280                0
1281                0
1282                0
1283                1
1284                0
1285                0
1286                0
1287                1
1288                0
1289                1
1290                0
1291                0
1292                1
1293                0
1294                1
1295                0
1296                0
1297                0
1298                0
1299                0
1300                1
1301                1
1302                1
1303                1
1304                1
1305                0
1306                1
1307                0
1308                0
1309                0

[418 rows x 1 columns]

In [104]:
submission.to_csv('submission.csv')

In [ ]:
fig = plt